### ISSUE TITLE
Not working with newest commit

### ISSUE THREAD

**Issue by xAffan** [std-nullptr/AmongUsMenu#107]
The new commit "Save any settings on change" causes some breaking bug which causes the following:
1) if version.dll is placed within game directory, the game won't launch.
2) if normal dll is injected then game will crash.

The same works with the last commit "Improvements" however and I can play fine with it

**Comment by std-nullptr** [comment]
We are going to need more information to look into this. You will need to build a debug version and attach Visual Studio to the process before injecting it. This will show you what line is causing the problem and you can provide a screenshot of this.

**Comment by std-nullptr** [comment]
Can you try the latest build?

**Comment by std-nullptr** [comment]
Closing as there has been no response.
