### ISSUE TITLE
Issue of Injection Result

### ISSUE THREAD

**Issue by bangsukism** [std-nullptr/AmongUsMenu#116]
Hi, I'm user of your Amongusmenu for a while and used to running really well,

But suddenly stop working and nothing appear menu, rader and everything. 

I did DELETE Key, Insert but doens't work..

I don't know what is the problem, I will attach file that after injected from GH injector and video that I inject by process hacker.

Can you please advice me how to run or fix this problem ? 

![Error 1](https://user-images.githubusercontent.com/75504423/103434325-a6d27280-4c4b-11eb-8ba7-10e9abc024a9.PNG)

https://user-images.githubusercontent.com/75504423/103434315-7f7ba580-4c4b-11eb-9996-2bc47c2627b2.mp4

**Comment by 083791** [comment]
On the video you just need to wait about 10-15 seconds. If that is not working move resources folder from the source code to executable directory

**Comment by 083791** [comment]
and use the release_version then put it to the executable directory and when it name is version.dll it will be automaticly injected

**Comment by manianac** [comment]
> On the video you just need to wait about 10-15 seconds. If that is not working move resources folder from the source code to executable directory

We no longer need the resources directory, you can delete it.

Just put version.dll build into the same folder as Among Us.exe, it will handle the rest.

**Comment by bangsukism** [comment]
> > On the video you just need to wait about 10-15 seconds. If that is not working move resources folder from the source code to executable directory
> 
> We no longer need the resources directory, you can delete it.
> 
> Just put version.dll build into the same folder as Among Us.exe, it will handle the rest.

Thank you so much I will try this!

Is there any chance to get dll file from github ?

**Comment by 083791** [comment]
Check my Git later. I will upload the pre-built dll. 🙂

**Comment by OsOmE1** [comment]
@083791 you are not supposed to do that just go to [](https://github.com/std-nullptr/AmongUsMenu/actions) and download the latest artifact
