### ISSUE TITLE
Players Tab Crashes

### ISSUE THREAD

**Issue by RealMVC** [std-nullptr/AmongUsMenu#14]
Clicking on the players tab will sometime cause a crash:
![image](https://user-images.githubusercontent.com/39596187/100542335-4351c100-3217-11eb-8c0e-091c0859d5ec.png)

The crash occurs in UnityPlayer.dll in function GetAllDeadBodies().

**Comment by KyreusR** [comment]
I'm unable to reproduce this issue.. Played 10 games on each map. The players tab didn't cause a crash for me.

**Comment by RealMVC** [comment]
Players Tab Crash 2:
![image](https://user-images.githubusercontent.com/39596187/100544355-13101f80-3223-11eb-936c-d966ee1c853c.png)
Seems to be caused by player->fields.myTasks being null.
