### ISSUE TITLE
Console bug

### ISSUE THREAD

**Issue by Fubanachi** [std-nullptr/AmongUsMenu#2]
> Issue with console

The issue is related with the voting results. The last voter will not be listed in the console, meaning it is not registered in the console at all. If there are 6 people voting, in the console it will show the first 5 voters while excluding the 6th(final) voter.

**Comment by marcohajek** [comment]
I couldn't confirm it till now, but there is a known issue with the scrolling where it's buggy and doesn't scroll to the last element in the list.
This would explain the issue, I'll check it later on after I've reinstalled my stuff

**Comment by OsOmE1** [comment]
i think it happens because when the last vote is cast the Update function is no longer called resulting in it not being registered

**Comment by manianac** [comment]
So the update function is still called, but MeetingHud::state changes to Results as the final vote is cast.  So we need to check votes on this state as well, #37 fixes this.

**Comment by RealMVC** [comment]
Fixed in Pull Request #38.
