### ISSUE TITLE
HItting "among us unity 2019.4.9f1_50fe8a171dd9" when injecting DLL

### ISSUE THREAD

**Issue by jjpaulino** [std-nullptr/AmongUsMenu#22]
Always hitting that error shortly after loading the game and right after injecting the DLL (either one of the available DLLs)

**Comment by KyreusR** [comment]
Which version of the game are you using?

**Comment by jjpaulino** [comment]
Among Us v2020.11.17s

**Comment by KyreusR** [comment]
Cracked/Steam?

**Comment by jjpaulino** [comment]
Cracked

**Comment by KyreusR** [comment]
Then you don't have the newest cracked version of v2020.11.17.
This game has two versions. you have to use the latest.
