### ISSUE TITLE
add option to select dleks

### ISSUE THREAD

**Issue by xAffan** [std-nullptr/AmongUsMenu#25]
it can be used when date is set to 1 april 2020, inverted left-right skelds

**Comment by fatraxx** [comment]
just add map "-1" in **HOST** Tab

**Comment by OsOmE1** [comment]
that won't work as the game checks if the date is the first of april

**Comment by xAffan** [comment]
https://github.com/Devilx86/ImpostorModmenu
this is possible. ^ download this from polarmods.com and you see it has an option to get Dleks and much more.
