### ISSUE TITLE
Chat Window Disappears When Typing 'E' or Space as Impostor

### ISSUE THREAD

**Issue by RealMVC** [std-nullptr/AmongUsMenu#27]
When typing in chat, the chat window will sometimes disappear. The chat button will disappear, and you will be unable to open the chat, but you can still hear the sound of other people chatting.

**Comment by jojozacscott713** [comment]
sorry but may I ask how to do this, I can't find the DLL files to put in the injector I'm also completely new to this.

**Comment by KyreusR** [comment]
This has nothing to do with this issue. Please look at the support chat on our discord.
