### ISSUE TITLE
Crash related to Camera Zoom

### ISSUE THREAD

**Issue by manianac** [std-nullptr/AmongUsMenu#30]
I'm getting sporadic crashes, and was able to catch this one in the debugger.

Exception thrown at 0x7AD64803 (UnityPlayer.dll) in Among Us.exe: 0xC0000005: Access violation reading location 0x000003C9.

I don't know the cause yet, assuming something corrupted with FollowerCam

![image](https://user-images.githubusercontent.com/2092573/100676794-96bb3080-3337-11eb-8e30-656553de0617.png)

**Comment by std-nullptr** [comment]
Believe this was fixed with #41
