### ISSUE TITLE
Report Button Is Visible In Lobby

### ISSUE THREAD

**Issue by RealMVC** [std-nullptr/AmongUsMenu#31]
While in a lobby, the report button is visible, even though it shouldn't be.
![image](https://user-images.githubusercontent.com/39596187/100775169-e863c980-33d0-11eb-90c2-c6c892260622.png)

**Comment by manianac** [comment]
Currently State.ShowHUD is always true.  It looks like it may have been a planned feature to hide the HUD, but for now a quick fix is to disable the always on activation.

This can be reworked in the future to have this option, as well as checking IsInGame() before activating the HUD.
