### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dencelle** [std-nullptr/AmongUsMenu#40]
![image](https://user-images.githubusercontent.com/483540/101221345-1f461380-364d-11eb-841a-22c76fb152f1.png)
address dump, can easily replicate if needed
`AmongUsClient__TypeInfo = 1590B8E0
GameData__TypeInfo = 1590E7B0
Palette__TypeInfo = 1780D8B8
PlayerControl__TypeInfo = 15700448
ShipStatus__TypeInfo = 15910EE0
GameOptionsData__TypeInfo = 1593BF08
Camera__TypeInfo = 15620958
Marshal_PtrToStringAnsi = 073CC8F0
Marshal_PtrToStringUni = 073CC900
Type_GetType = 081639C0
Component_get_gameObject = 07A71460
Component_get_transform = 07A714F0
Component_get_tag = 07A71490
GameObject_set_layer = 07A73980
LayerMask_NameToLayer = 07A74670
Object_1_FindObjectsOfType = 07971440
Scene_GetNameInternal = 0797A120
SceneManager_Internal_ActiveSceneChanged = 07979C40
Transform_get_position = 07980AE0
Transform_set_position = 07980F30
Vector2_Distance = 07982020
Collider2D_OverlapPoint = 0834E5F0
Application_get_version = 07A6D8A0
Renderer_set_enabled = 07979A90
Camera_GetAllCameras = 07A6FAF0
Camera_get_allCamerasCount = 07A6FAA0
Camera_get_main = 07A70420
Camera_set_orthographicSize = 07A70600
Camera_get_orthographicSize = 07A70470
AutoOpenDoor_DoUpdate = 0801CE00
CustomNetworkTransform_RpcSnapTo = 082FA650
DeadBody_get_TruePosition = 080523D0
GameData_GetPlayerById = 079EA390
GameOptionsData_Deserialize = 07DA7BD0
GameOptionsData_Deserialize_1 = 07DA7F40
HatManager_GetUnlockedHats = 07D9EA20
HatManager_GetUnlockedPets = 07D9EC10
HatManager_GetUnlockedSkins = 07D9ECE0
KeyboardJoystick_Update = 0763AD00
MeetingHud_Awake = 0729C860
MeetingHud_Close = 0729E6A0
MeetingHud_Update = 072A9B80
NormalPlayerTask_get_IsComplete = 07B39A30
NormalPlayerTask_NextStep = 07B3C1F0
PlainDoor_SetDoorway = 07B94920
PlayerControl_CompleteTask = 075BD430
PlayerControl_FixedUpdate = 075BEFB0
PlayerControl_get_Data = 075CB4F0
PlayerControl_GetTruePosition = 075BFE10
PlayerControl_RpcSyncSettings = 075C9E20
PlayerControl_CmdReportDeadBody = 075BD310
PlayerControl_MurderPlayer = 075C5620
PlayerControl_ReportDeadBody = 075C2AE0
PlayerControl_RpcSetInfected = 075C9880
ShipStatus_CalculateLightRadius = 07864300
ShipStatus_OnEnable = 0786A630
ShipStatus_RpcCloseDoorsOfType = 0786BAC0
ShipStatus_RpcRepairSystem = 0786BB70
ShipStatus_RepairSystem = 0786BA20
StatsManager_get_BanPoints = 07504720
StatsManager_get_BanMinutesLeft = 07504820
StatsManager_get_AmBanned = 07504A20
Vent_CanUse = 07CD33F0
Vent_get_UsableDistance = 07CD6950
Vent_EnterVent = 07CD3E50
Vent_ExitVent = 07CD60B0
HudManager_Update = 07942F00
HudManager_ShowMap = 07942B40
HudManager_SetHudActive = 079425A0
ChatController_AddChat = 07E52FC0
ChatController_SetVisible = 07E60E00
ChatBubble_SetName = 074E1700
InnerNetClient_get_AmHost = 0793E890`

**Comment by KyreusR** [comment]
Please tell me how to reproduce this issue, and I'll have a look

**Comment by dencelle** [comment]
entering game and leaving games, i just keep doing it over and over and it happens every 1/3 games or so

**Comment by RealMVC** [comment]
Fixed in #41.
