### ISSUE TITLE
Exiting vents does not show up in event log as of 2020.12.3s

### ISSUE THREAD

**Issue by dencelle** [std-nullptr/AmongUsMenu#42]
![image](https://user-images.githubusercontent.com/483540/101226363-d6488c00-3659-11eb-9d53-79f7cba1838c.png)
seems the venting event is only being called when the imposter is entering a vent but is not getting called when they leave a vent.

**Comment by KyreusR** [comment]
Further note: VENT IN events gets registered AFTER hopping out of the vent again
