### ISSUE TITLE
Double Radar Bug

### ISSUE THREAD

**Issue by RealMVC** [std-nullptr/AmongUsMenu#6]
Radar sometimes gets duplicated.
![image](https://user-images.githubusercontent.com/39596187/100521756-865a5880-3173-11eb-91f0-0d42572598b8.png)

This happened after using radar in a previous game, and then playing a new game with radar on.

**Comment by MrKaliostro** [comment]
Wow, double the info bro!

**Comment by RealMVC** [comment]
Either extremely rare or patched by changes to the radar. Closed because I can't reproduce the issue.
