### ISSUE TITLE
Crashing game

### ISSUE THREAD

**Issue by 083791** [std-nullptr/AmongUsMenu#89]
Hello. Recently I've updated the source code of this hack and when I inject it to the among us process game is crashing. How to fix it?

**Comment by OsOmE1** [comment]
Please attach a stack trace or any sort of debug info/crash log this doesn't tell me in any way what is going wrong. Also what branch did you checkout from and what source code have you updated?

**Comment by Zayoe4** [comment]
> Please attach a stack trace or any sort of debug info/crash log this doesn't tell me in any way what is going wrong. Also what branch did you checkout from and what source code have you updated?

How do you get debug info?

**Comment by std-nullptr** [comment]
Closing this as there are been no updates, we need you to build the debug build in Visual Studio and attached it to the process before injecting.  Visual Studio will then show what is causing the crash which you can provide a screenshot for.
