### ISSUE TITLE
Dead people are showed as voting in the console

### ISSUE THREAD

**Issue by Fubanachi** [std-nullptr/AmongUsMenu#91]
![image](https://user-images.githubusercontent.com/35321215/101910974-afaac800-3bfa-11eb-8248-67a1403390f2.png)

As you can see in the picture, all the ones who skipped were dead/lefted the game. But it shows them skipping in the console, this is new since the previous builds would not show dead/leavers skipping because it just did not register into the console.

**Comment by OsOmE1** [comment]
Thank you for your bug report I’ll look into it

**Comment by manianac** [comment]
Is it showing all dead people, or those that quit during the meeting?

**Comment by Fubanachi** [comment]
Both. 
![image](https://user-images.githubusercontent.com/35321215/102552826-34cd2b80-4098-11eb-8204-97f9667e3a85.png)

In this picture, Orange,Blue,Pink was already dead/lefted the game. Their votes are still in the console. This was fixed but became an issue in the newest build.
